server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /dine_in_customer
  forward-headers-strategy: framework

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: scan-dine-customer-service

  datasource:
    customer-ds:
      url: jdbc:postgresql://localhost:5432/scan_dineIn?currentSchema=customers
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: CustomerHikariPool

    restaurant-ds:
      url: jdbc:postgresql://localhost:5432/scan_dineIn?currentSchema=restaurants
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: RestaurantHikariPool

    table-ds:
      url: jdbc:postgresql://localhost:5432/scan_dineIn?currentSchema=tables
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: TableHikariPool

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

jwt:
  secret: YOUR_JWT_SECRET_HERE

twilio:
  account-sid: YOUR_TWILIO_ACCOUNT_SID
  auth-token: YOUR_TWILIO_AUTH_TOKEN
  from-number: YOUR_TWILIO_FROM_NUMBER

springdoc:
  packages-to-scan: com.example.scan_dineCustomer

