package com.example.scan_dineCustomer.enums;

public enum StatusCode {
    // CUSTOM BUSINESS CODES 1xxxx
    UNABLE_TO_CREATE_TRANSACTIONS(10001, 1, "UNABLE_TO_CREATE_TRANSACTIONS"),
    UNABLE_TO_CREATE_RAZOR_PAY_ORDER(10002, 1, "UNABLE_TO_CREATE_RAZOR_PAY_ORDER"),
    PAYMENT_DETAILS_NOT_FOUND(10003, 1, "PAYMENT_DETAILS_NOT_FOUND"),
    REFUND_AMOUNT_CANNOT_BE_GREATER_THAN_TRANSACTION_AMOUNT(10004, 1, "REFUND_AMOUNT_CANNOT_BE_GREATER_THAN_TRANSACTION_AMOUNT"),
    ISSUE_WITH_RAZORPAY(10005, 1, "ISSUE_WITH_RAZORPAY"),
    REFUND_ENTITY_CANNOT_BE_CREATED(10006, 1, "REFUND_ENTITY_CANNOT_BE_CREATED"),
    UNABLE_TO_CANCEL_PINE_LABS_TRANSACTION(10007, 1, "UNABLE_TO_CANCEL_PINE_LABS_TRANSACTION"),
    RESTAURANT_NOT_FOUND(10008, 1, "RESTAURANT_NOT_FOUND"),
    DATA_ISSUE_FOR_THE_RETAIL(10009, 1, "DATA_ISSUE_FOR_THE_RETAIL"),
    UNABLE_TO_UPLOAD_IMAGE(10010, 1, "UNABLE_TO_UPLOAD_IMAGE"),
    DATA_ISSUE_FOR_THE_RETAIL_DETAILS(10011, 1, "DATA_ISSUE_FOR_THE_RETAIL_DETAILS"),
    ISSUE_WITH_WAREHOUS_RETAIL_MAPPING(10012, 1, "ISSUE_WITH_WAREHOUS_RETAIL_MAPPING"),
    NO_ADDRESSES_FOUND_FOR_THE_RETAIL(10013, 1, "NO_ADDRESSES_FOUND_FOR_THE_RETAIL"),
    BRANCH_CREATION_FAILED(10014, 1, "BRANCH_CREATION_FAILED"),
    ISSUE_WITH_BRANCH_CREATION_DATA(10015, 1, "ISSUE_WITH_BRANCH_CREATION_DATA"),
    BRANCH_NOT_FOUND(10016, 1, "BRANCH_NOT_FOUND"),
    ISSUE_WITH_ADDRESS_CREATION_DATA(10017, 1, "ISSUE_WITH_ADDRESS_CREATION_DATA"),
    RETAIL_DETAILS_NOT_FOUND(10018, 1, "RETAIL_DETAILS_NOT_FOUND"),
    ADDRESS_NOT_FOUND(10019, 1, "ADDRESS_NOT_FOUND"),
    ISSUE_WITH_ADDRESS_UPDATE_DATA(10020, 1, "ISSUE_WITH_ADDRESS_UPDATE_DATA"),
    UNABLE_TO_ADD_ADDRESS(10021, 1, "UNABLE_TO_ADD_ADDRESS"),
    ISSUE_WITH_RETAIL_USER_CREATION_DATA(10022, 1, "ISSUE_WITH_RETAIL_USER_CREATION_DATA"),
    UNABLE_TO_SAVE_CUSTOMER_DATA(10023, 1, "Unable to save customer data"),
    ISSUE_WITH_RETAIL_CUSTOMER_CREATION_DATA(10024, 1, "ISSUE_WITH_RETAIL_CUSTOMER_CREATION_DATA"),
    RETAIL_USER_NOT_FOUND(10025, 1, "RETAIL_USER_NOT_FOUND"),
    RETAIL_CUSTOMER_NOT_FOUND(10026, 1, "RETAIL_CUSTOMER_NOT_FOUND"),
    CONTACT_NOT_FOUND(10027, 1, "CONTACT_NOT_FOUND"),
    UNABLE_TO_UPDATE_CONTACT(10028, 1, "UNABLE_TO_UPDATE_CONTACT"),
    ISSUE_WITH_CONTACT_CREATION_DATA(10029, 1, "ISSUE_WITH_CONTACT_CREATION_DATA"),
    UNABLE_TO_SAVE_CONTACT_DATA(10030, 1, "UNABLE_TO_SAVE_CONTACT_DATA"),
    CUSTOMER_MAPPING_EXISTS_FOR_RETAIL(10031, 1, "CUSTOMER_MAPPING_EXISTS_FOR_RETAIL"),
    ISSUE_WITH_KYC_CREATION_DATA(10032, 1, "ISSUE_WITH_KYC_CREATION_DATA"),
    UNABLE_TO_SAVE_KYC_DATA(10033, 1, "UNABLE_TO_SAVE_KYC_DATA"),
    KYC_DOCUMENT_VERIFICATION_PENDING(10034, 1, "KYC_DOCUMENT_VERIFICATION_PENDING"),
    NO_KYC_FOUND_FOR_THE_ENTITY(10035, 1, "NO_KYC_FOUND_FOR_THE_ENTITY"),
    NO_KYC_DOCUMENT_FOUND(10036, 1, "NO_KYC_DOCUMENT_FOUND"),
    ITEM_ALREADY_EXISTS(10037, 1, "PAN_NUMBER_ALREADY_EXISTS"),
    KYC_EXISTS_FOR_THE_ENTITY(10038, 1, "KYC_EXISTS_FOR_THE_ENTITY"),
    DOCUMENT_CANNOT_BE_ADDED_TO_PROCESSES_KYCs(10039, 1, "DOCUMENT_CANNOT_BE_ADDED_TO_PROCESSES_KYCs"),
    RETAIL_USER_ALREADY_EXISTS_FOR_THE_RETAIL(10040, 1, "RETAIL_USER_ALREADY_EXISTS_FOR_THE_RETAIL"),
    ISSUE_WITH_ADDRESS_DATA(10041, 1, "RETAIL_USER_ALREADY_EXISTS_FOR_THE_RETAIL"),
    ENTER_UNIQUE_ADDRESS_NAME(10042, 1, "ENTER_UNIQUE_ADDRESS_NAME"),
    RETAIL_ALREADY_EXISTS_WITH_SIMILAR_DETAILS(10043, 1, "RETAIL_ALREADY_EXISTS_WITH_SIMILAR_DETAILS"),
    ISSUE_WITH_UPDATE_DATA(10044, 1, "ISSUE_WITH_UPDATE_DATA"),
    BRANCH_ALREADY_EXISTS_WITH_SAME_NAME_FOR_ORG(10045, 1, "BRANCH_ALREADY_EXISTS_WITH_SAME_NAME_FOR_ORG"),
    NO_RETAILS_FOUND(10046, 1, "NO_RETAILS_FOUND"),
    GST_DETAILS_NOT_FOUND_FOR_BRANCH(10047, 1, "GST_DETAILS_NOT_FOUND_FOR_BRANCH"),
    BRANCH_AND_RETAIL_COMBINATION_NOT_FOUND(10048, 1, "BRANCH_AND_RETAIL_COMBINATION_NOT_FOUND"),
    UNABLE_TO_CREATE_SUPPORT_TICKET(10049, 1, "UNABLE_TO_CREATE_SUPPORT_TICKET"),
    TYPE_NOT_FOUND(10050, 1, "TYPE_NOT_FOUND"),
    UNABLE_TO_CREATE_TASK(10051, 1, "UNABLE_TO_CREATE_TASK"),
    UNABLE_TO_SAVE_TASK(10052, 1, "UNABLE_TO_SAVE_TASK"),
    TASK_TYPE_EXISTS_WITH_SIMILAR_DETAILS(10053, 1, "TASK_TYPE_EXISTS_WITH_SIMILAR_DETAILS"),
    UNABLE_TO_CREATE_TASK_TYPE_OBJECT(10054, 1, "UNABLE_TO_CREATE_TASK_TYPE_OBJECT"),
    UNABLE_TO_SAVE_TASK_TYPE_OBJECT(10055, 1, "UNABLE_TO_SAVE_TASK_TYPE_OBJECT"),
    SUB_TYPE_WITH_SIMILAR_DETAILS_ALREADY_EXISTS(10056, 1, "SUB_TYPE_WITH_SIMILAR_DETAILS_ALREADY_EXISTS"),
    ISSUE_WHILE_CREATING_SUBTYPE(10056, 1, "ISSUE_WHILE_CREATING_SUBTYPE"),
    SUB_TYPE_NOT_FOUND(10056, 1, "SUB_TYPE_NOT_FOUND"),
    TASK_EXISTS_WITH_SIMILAR_DETAILS(10057, 1, "TASK_EXISTS_WITH_SIMILAR_DETAILS"),
    TASK_NOT_FOUND(10058, 1, "TASK_NOT_FOUND"),
    ISSUE_WHILE_CREATING_MAPPING(10059, 1, "ISSUE_WHILE_CREATING_MAPPING"),
    UNABLE_TO_CREATE_TERMS_OF_TRADE(10060, 1, "UNABLE TO CREATE TERMS OF TRADE"),
    UNABLE_TO_DELETE_TERMS_OF_TRADE(10061, 1, "UNABLE TO DELETE TERMS OF TRADE"),
    UNABLE_TO_UPDATE_TERMS_OF_TRADE(10062, 1, "UNABLE TO UPDATE TERMS OF TRADE"),
    UNABLE_TO_UPLOAD_DOCUMENTS(10063, 1, "UNABLE TO UPLOAD DOCUMENTS"),
    UNABLE_TO_SAVE_DOCUMENTS(10064, 1, "UNABLE TO SAVE DOCUMENTS"),
    CONFIGURATION_EXISTS_FOR_THE_ORGANIZATION(10065, 1, "CONFIGURATION_EXISTS_FOR_THE_ORGANIZATION"),
    UNABLE_TO_ADD_DATA(10066, 1, "UNABLE_TO_ADD_DATA"),
    UNABLE_TO_DELETE_DATA(10066, 1, "UNABLE_TO_DELETE_DATA"),
    UNABLE_TO_UPDATE(10066, 1, "UNABLE_TO_UPDATE"),
    NO_UPDATE_REQUIRED(10067, 1, "NO_UPDATE_REQUIRED"),
    DEFAULT_PRINTER_ALREADY_EXISTS_FOR_LOCATION(10067, 1, "DEFAULT_PRINTER_ALREADY_EXISTS_FOR_LOCATION"),

    STORE_CONFIGURATION_ALREADY_EXISTS_FOR_LOCATION(10068, 1, "STORE_CONFIGURATION_ALREADY_EXISTS_FOR_LOCATION"),
    UNABLE_TO_MAP_STORE_CONFIGURATION(10069,1,"UNABLE_TO_MAP_STORE_CONFIGURATION"),

    UNABLE_TO_SAVE_STORE_CONFIGURATION(10070,1,"UNABLE_TO_SAVE_STORE_CONFIGURATION"),

    NO_DATA_IN_UPDATE_DETAIL_REQUEST(10071,1,"NO_DATA_IN_UPDATE_DETAIL_REQUEST"),

    NO_DATA_IN_CREATE_DETAIL_REQUEST(10072, 1, "NO_DATA_IN_CREATE_DETAIL_REQUEST"),

    UNABLE_TO_MAP(10073, 1, "UNABLE_TO_MAP"),

    UNABLE_TO_FETCH_DATA_FROM_USER_SERVICE(10074, 1, "UNABLE_TO_FETCH_DATA_FROM_USER_SERVICE"),

    UNABLE_TO_FETCH_SECONDARY_LOCATION_AND_SECONDARY_ORGANIZATION(10075, 1, "UNABLE_TO_FETCH_SECONDARY_LOCATION_AND_SECONDARY_ORGANIZATION"),

    UNABLE_TO_CREATE_BULK_LEDGER_CUSTOMER(10076, 1, "UNABLE_TO_CREATE_BULK_LEDGER_CUSTOMER"),

    UNABLE_TO_CREATE_BRANCH_CONFIG(10068, 1, "UNABLE_TO_CREATE_BRANCH_CONFIG"),

    TERMINAL_CONFIG_ALREADY_EXISTS_FOR_THIS_TERMINAL(10068, 1, "TERMINAL_CONFIG_ALREADY_EXISTS_FOR_THIS_TERMINAL"),
    UNABLE_TO_UPDATE_BRANCH_CONFIG(10069, 1, "UNABLE_TO_UPDATE_BRANCH_CONFIG"),

    UNABLE_TO_UPDATE_TERMINAL_CONFIG(10070, 1, "UNABLE_TO_UPDATE_TERMINAL_CONFIG"),
    UNABLE_TO_DELETE_TERMINAL_CONFIG(10071, 1, "UNABLE_TO_DELETE_TERMINAL_CONFIG"),

    UNABLE_TO_DELETE_BRANCH_CONFIG(10072, 1, "UNABLE_TO_DELETE_BRANCH_CONFIG"),

    BRANCH_CONFIG_ALREADY_EXISTS(10073, 1, "BRANCH_CONFIG_ALREADY_EXISTS"),

    UNABLE_TO_MAP_BRANCH_CONFIG(10074, 1, "UNABLE_TO_MAP_BRANCH_CONFIG"),
    UNABLE_TO_SAVE_BRANCH_CONFIG(10075, 1, "UNABLE_TO_SAVE_BRANCH_CONFIG"),
    UNABLE_TO_MAP_TERMINAL_CONFIG(10076, 1, "UNABLE_TO_MAP_TERMINAL_CONFIG"),

    UNABLE_TO_SAVE_TERMINAL_CONFIG(10078, 1, "UNABLE_TO_SAVE_TERMINAL_CONFIG"),
    UNABLE_TO_FETCH_TERMINAL_DATA_FROM_BUSINESS_SERVICE(10079, 1, "UNABLE_TO_FETCH_TERMINAL_DATA_FROM_BUSINESS_SERVICE"),

    TERMINAL_IS_NOT_ASSOCIATED_WITH_BRANCH(10080, 1, "TERMINAL_IS_NOT_ASSOCIATED_WITH_BRANCH"),
    TERMINAL_IS_NOT_ASSOCIATED_WITH_RETAIL(10081, 1, "TERMINAL_IS_NOT_ASSOCIATED_WITH_RETAIL"),

    UNABLE_TO_FIND_CUSTOMER(10082, 1, "UNABLE_TO_FIND_CUSTOMER"),
    UNABLE_TO_MAP_TEMPLATE_REQUEST_TO_ENTITY(10083, 1, "UNABLE_TO_MAP_TEMPLATE_REQUEST_TO_ENTITY"),
    UNABLE_TO_SAVE_TEMPLATE(10084, 1, "UNABLE_TO_SAVE_TEMPLATE"),
    UNABLE_TO_MAP_TEMPLATE_ENTITY_TO_DTO(10085, 1, "UNABLE_TO_MAP_TEMPLATE_ENTITY_TO_DTO"),
    TEMPLATE_ALREADY_EXIST(10086, 1, "TEMPLATE_ALREADY_EXIST"),
    UNABLE_TO_CREATE_TEMPLATE(10087, 1, "UNABLE_TO_CREATE_TEMPLATE"),
    UNABLE_TO_SAVE_DATA(10088, 1, "UNABLE_TO_SAVE_DATA"),
    UNABLE_TO_MAP_PERIPHERAL_REQUEST_TO_ENTITY(10089, 1, "UNABLE_TO_MAP_PERIPHERAL_REQUEST_TO_ENTITY"),
    UNABLE_TO_SAVE_PERIPHERAL(10090, 1, "UNABLE_TO_SAVE_PERIPHERAL"),
    UNABLE_TO_MAP_PERIPHERAL_ENTITY_TO_DTO(10091, 1, "UNABLE_TO_MAP_PERIPHERAL_ENTITY_TO_DTO"),
    UNABLE_TO_UPDATE_PERIPHERAL(10092, 1, "UNABLE_TO_UPDATE_PERIPHERAL"),
    PRINTER_IS_ALREADY_SETUP_IN_OUR_APP(10093, 1, "PRINTER_IS_ALREADY_SETUP_IN_OUR_APP"),
    TEMPLATE_WITH_SAME_NAME_ALREADY_EXISTS(10094, 1, "TEMPLATE_WITH_SAME_NAME_ALREADY_EXISTS"),
    PRINTER_CONFIG_NOT_FOUND(10095, 1, "PRINTER_CONFIG_NOT_FOUND"),
    UNABLE_TO_MAP_PRINTER_CONFIG_RESPONSE(10096, 1, "UNABLE_TO_MAP_PRINTER_CONFIG_RESPONSE"),
    UNABLE_TO_SAVE_PRINTER_CONFIG(10097, 1, "UNABLE_TO_SAVE_PRINTER_CONFIG"),
    UNABLE_TO_MAP_PRINTER_CONFIG(10098, 1, "UNABLE_TO_MAP_PRINTER_CONFIG"),
    PRINTER_CONFIG_ALREADY_EXISTS(10099, 1, "PRINTER_CONFIG_ALREADY_EXISTS"),
    UNABLE_TO_UPDATE_PRINTER_CONFIG(10100, 1, "UNABLE_TO_UPDATE_PRINTER_CONFIG"),
    UNABLE_TO_MAP_BILLING_REQUEST(10101, 1, "UNABLE_TO_MAP_BILLING_REQUEST"),
    UNABLE_TO_SAVE_BILLING_INFO(10102, 1, "UNABLE_TO_SAVE_BILLING_INFO"),
    UNABLE_TO_MAP_BILLING_ENTITY(10103, 1, "UNABLE_TO_MAP_BILLING_ENTITY"),
    UNABLE_TO_SAVE_PRINT_JOB_ROUTINGS(10104, 1, "UNABLE_TO_SAVE_PRINT_JOB_ROUTINGS"),
    UNABLE_TO_MAP_PRINT_JOB_ROUTING_ENTITIES(10105, 1, "UNABLE_TO_MAP_PRINT_JOB_ROUTING_ENTITIES"),
    BRANCH_ALREADY_EXISTS_WITH_SAME_DOMAIN_NAME(10106, 1, "BRANCH_ALREADY_EXISTS_WITH_SAME_DOMAIN_NAME"),
    INVALID_LATITUDE_OR_LONGITUDE(10107, 1, "Latitude must be between -90 and 90, and Longitude must be between -180 and 180"),

    // custom code for HRMS
    DEPARTMENT_ID_IS_INVALID_OR_DELETED(20001,1,"DEPARTMENT_ID_IS_INVALID_OR_DELETED"),
    DESIGNATION_ID_IS_INVALID_OR_DELETED(20002,1,"DESIGNATION_ID_IS_INVALID_OR_DELETED"),
    TEAM_ID_IS_INVALID_OR_DELETED(20003,1,"TEAM_ID_IS_INVALID_OR_DELETED"),
    EMPLOYEE_ID_IS_INVALID(20004,1,"EMPLOYEE ID IS INVALID"),
    EMPLOYEE_ID_NOT_FOUND(20002,1,"EMPLOYEE ID NOT FOUND"),
    DEPARTMENT_ID_NOT_FOUND(20003,1,"DEPARTMENT ID NOT FOUND"),
    HOLIDAY_ID_NOT_FOUND(20004,1,"HOLIDAY ID NOT FOUND"),
    ATTENDANCE_NOT_FOUND(20005,1,"ATTENDANCE NOT FOUND"),
    INVALID_DOCUMENT_TYPE(20006,1,"INVALID_DOCUMENT_TYPE"),
    DEPARTMENT_NAME_ALREADY_PRESENT(20002,1,"DEPARTMENT NAME ALREADY PRESENT"),
    INVALID_EMAIL_FORMAT(20003,1,"INVALID_EMAIL_FORMAT"),
    INVALID_NAME_FORMAT(20004,1,"INVALID_NAME_FORMAT"),
    INVALID_PHONE_NUMBER_FORMAT(20005,1,"INVALID_PHONE_NUMBER_FORMAT"),
    LEAVE_ID_NOT_FOUND(20006,1,"LEAVE ID NOT FOUND"),
    INVALID_LEAVE_YEAR(20007,1,"INVALID_LEAVE_YEAR"),
    MAX_LEAVE_DAYS_EXCEEDED(20008,1,"MAX_LEAVE_DAYS_EXCEEDED"),
    MAX_LEAVE_INSTANCE_EXCEEDED(20009,1,"MAX_LEAVE_INSTANCE_EXCEEDED"),
    INVALID_LEAVE_DATES(20010,1,"INVALID_LEAVE_DATES"),
    LEAVE_BALANCE_EXCEEDED(20011,1,"LEAVE_BALANCE_EXCEEDED"),
    MAX_LEAVE_BALANCE_EXCEEDED(20012,1,"MAX_LEAVE_BALANCE_EXCEEDED"),
    DEPARTMENT_MASTER_ALREADY_FOUND(20013,1,"DEPARTMENT MASTER ALREADY FOUND"),
    SALARY_COMPONENT_ID_NOT_FOUND(20014,1,"SALARY_COMPONENT_ID_NOT_FOUND"),
    ALREADY_FOUND(20015,1,"ALREADY_FOUND"),
    INSUFFICIENT_LEAVE_BALANCE(20016,1,"INSUFFICIENT_LEAVE_BALANCE"),
    LEAVE_NOT_APPLICABLE(20017,1,"LEAVE_NOT_APPLICABLE"),
    PHONE_NUMBER_ALREADY_EXISTS(20018,1,"PHONE_NUMBER_ALREADY_EXISTS"),

    // Base codes
    OK(200, 0, "Success"),
    SERVER_ERROR(400, 1, "Failed!"),
    SUCCESS(201, 0, "Success"),
    SUCCESS_PAYMENT(202, 0, "Payment Details Processed Successfully"),
    NO_DATA_CHANGE_REQUIRED(200, 0, "NO_DATA_CHANGE_REQUIRED"),

    // HRMS
    LEAVE_STATUS_UPDATED(200,0,"LEAVE STATUS UPDATED"),
    LEAVE_APPLIED_SUCCESSFULLY(200,0,"LEAVE APPLIED SUCCESSFULLY"),
    DEPARTMENT_ALREADY_FOUND(200,1,"DEPARTMENT ALREADY FOUND"),
    DESIGNATION_ALREADY_FOUND(200,1,"DESIGNATION ALREADY FOUND"),
    EMPLOYEE_ALREADY_FOUND(200,1,"EMPLOYEE ALREADY FOUND"),
    SHIFT_ALREADY_EXISTS(200,1,"SHIFT ALREADY EXISTS"),
    HOLIDAY_ALREADY_FOUND(200,1,"HOLIDAY ALREADY FOUND"),
    LEAVE_ALREADY_APPLIED_FOR_THAT_DAY(200,1,"LEAVE_ALREADY_APPLIED_FOR_THAT_DATE"),
    LEAVE_ALREADY_EXISTS(200,1,"LEAVE_ALREADY_EXISTS"),
    DEPARTMENT_NAME_ALREADY_EXISTS(200,1,"DEPARTMENT NAME ALREADY EXISTS"),
    TEAM_ALREADY_FOUND(200,1,"TEAM ALREADY FOUND"),
    EMAIL_ALREADY_EXISTS(200,1,"EMAIL ALREADY EXISTS"),
    DELETED_SUCCESSFULLY(200,0,"DELETED SUCCESSFULLY"),
    APPROVED_SUCCESSFULLY(200,0,"APPROVED SUCCESSFULLY"),
    DOCUMENT_UPLOADED_SUCCESSFULLY(200,0,"DOCUMENT UPLOADED SUCCESSFULLY"),
    LEAVE_REJECTED(200,0,"LEAVE REJECTED"),
    DEPARTMENT_CREATED(200,0,"DEPARTMENT_CREATED"),


    NO_DATA_FOUND_MATCHING_THE_FILTER(204, 0, "No data found matching the filters"),

    //Task
    LOCATION_ID_NOT_FOUND(200,1,"LOCATION ID NOT FOUND"),
    ORGANIZATION_ID_NOT_FOUND(200,1,"ORGANIZATION ID NOT FOUND"),
    PROJECT_ID_IS_INVALID_OR_DELETED(20001,1,"PROJECT_ID_IS_INVALID_OR_DELETED"),
    TASK_ID_IS_INVALID_OR_DELETED(20002,1,"TASK_ID_IS_INVALID_OR_DELETED"),
    EPIC_ID_IS_INVALID_OR_DELETED(20003,1,"EPIC_ID_IS_INVALID_OR_DELETED"),
    EPIC_ID_OR_PROJECT_ID_NOT_FOUND(20003,1,"EPIC ID OR PROJECT ID NOT FOUND"),
    SOURCE_OR_DESTINATION_LOCATION_ID_NOT_FOUND(20004,1,"SOURCE OR DESTINATION LOCATION ID NOT FOUND"),
    TASK_ID_IS_INVALID(20004,1,"TASK_ID_IS_INVALID"),
    TASK_ID_NOT_FOUND(20005,1,"TASK ID NOT FOUND"),
    LINKED_TASK_IDS_NOT_FOUND(20006,1,"LINKED TASK IDS NOT FOUND"),
    TICKET_ID_NOT_FOUND(20006,1,"TICKET ID NOT FOUND"),
    LOCATION_ID_ORGANIZATION_ID_NOT_VALID(20006,1,"LOCATION ID ORGANIZATION ID NOT VALID"),
    EPIC_ID_NOT_FOUND(20006,1,"EPIC ID NOT FOUND"),
    SUBTASK_ID_NOT_FOUND(20006,1,"SUBTASK ID NOT FOUND"),
    COMMENT_ID_NOT_FOUND(20006,1,"COMMENT ID NOT FOUND"),
    PROJECT_ID_NOT_FOUND(20007,1,"PROJECT ID NOT FOUND"),
    FEATURE_ID_NOT_FOUND(20008,1,"FEATURE ID NOT FOUND"),
    PROJECT_NAME_NOT_FOUND(20008,1,"PROJECT NAME NOT FOUND"),
    PRIMARY_TASK_ID_NOT_FOUND(20009, 1,"PRIMARY TASK ID NOT FOUND"),
    SPRINT_ID_NOT_FOUND(20010,1,"SPRINT ID NOT FOUND"),
    LAST_SPRINT_NOT_ENDED_YET(20010,1,"LAST SPRINT NOT ENDED YET"),
    COMPLETE_LAST_SPRINT_BEFORE_STARTING_NEW_ONE(20010,1,"COMPLETE LAST SPRINT BEFORE STARTING NEW ONE"),
    TWO_SPRINTS_CANNOT_HAVE_SAME_START_DATE(20010,1,"TWO SPRINTS CANNOT HAVE SAME START DATE"),
    SPRINT_START_END_SHOULD_NOT_BE_SAME_END_DATE_OF_LAST_SPRINT(20010,1,"SPRINT START END SHOULD NOT BE SAME END DATE OF LAST SPRINT"),
    UPDATED_BY_NOT_FOUND(20011,1,"UPDATED BY NOT FOUND"),
    LINKED_SUBTASK_NOT_FOUND(20012,1,"LINKED SUBTASK NOT FOUND"),
    FEATURE_ALREADY_FOUND(200,0,"FEATURE ALREADY FOUND"),
    PROJECT_ALREADY_FOUND(200,0,"PROJECT ALREADY FOUND"),
    DATA_COULD_NOT_BE_SAVED(200,1,"DATA COULD NOT BE SAVED"),
    INVALID_STATUS(200,1,"INVALID STATUS"),
    NO_TIMESHEET_FOUND_FOR_ID(200,1,"NO TIMESHEET FOUND FOR ID"),
    ATTACHMENT_ID_NOT_FOUND(200,1,"ATTACHMENT ID NOT FOUND"),
    DATE_IS_MISSING(20013,1,"DATE_IS_MISSING"),
    TASK_TYPE_ALREADY_EXISTS(200,1,"TASK_TYPE_ALREADY_EXISTS"),

    // Server & security error codes
    NO_DATA(300, 2, "No data found!"),
    INTERNAL_SERVER_ERROR(500, 1, "Sorry! Something went wrong."),
    BAD_REQUEST(400, 1, "Bad Request"),
    PLEASE_TRY_LATER(10060, 1, "PLEASE_TRY_LATER"),

    //RETAIL CUSTOMERS
    ADDRESS_WITH_SAME_TYPE_EXISTS(30001, 1, "ADDRESS_WITH_SAME_TYPE_EXISTS"),
    UNABLE_TO_CREATE_ADDRESS(30002, 1, "UNABLE_TO_CREATE_ADDRESS"),
    UNABLE_TO_UPDATE_ADDRESS(30003, 1, "UNABLE_TO_UPDATE_ADDRESS"),
    OTHER_NAME_REQUIRED(30004, 1, "OTHER_NAME_REQUIRED"),
    SECONDARY_RETAIL_ALREADY_EXIST(30005,1,"SECONDARY_RETAIL_ALREADY_EXIST"),
    // PIN VERIFICATION
    PIN_VERIFICATION_FAILED(30006, 1, "Pin Verification Failed."),
    //Table & Layout
    TABLE_NOT_FOUND(1001, 1, "Selected table not found or inactive"),
    TABLE_NOT_AVAILABLE(1002, 1, "Selected table is not available for the requested time slot"),
    TABLE_ALREADY_BOOKED_FOR_CART(1003, 1, "Selected table is already booked for the current cart"),
    TABLE_LAYOUT_NOT_FOUND(1004, 1, "Table layout relation not found or inactive"),
    TABLE_AVAILABLE(1005, 0, "Selected table is available for booking");


    private Integer code;
    private Integer errorState;
    private String statusMessage;

    StatusCode(Integer code, Integer errorState, String statusMessage) {
        this.code = code;
        this.statusMessage = statusMessage;
        this.errorState = errorState;
    }

    public StatusCode getByStatusCode(Integer code) {
        StatusCode[] values = values();
        for (StatusCode statusCode : values) {
            if (statusCode.getCode().equals(code)) {
                return statusCode;
            }
        }
        return StatusCode.SERVER_ERROR;
    }

    public Integer getCode() {
        return this.code;
    }

    public String getStatusMessage() {
        return this.statusMessage;
    }

    public Integer getErrorState() {
        return errorState;
    }
}

